name: Build and Deploy Demo

# This workflow runs on any push to the 'demo' branch
on:
  push:
    branches: [ "demo" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: View/package-lock.json

      - name: Install Dependencies
        run: npm install
        working-directory: ./View

      - name: Build Project
        run: npm run build
        working-directory: ./View

      - name: Deploy to 'deploy' Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: deploy
          publish_dir: ./View/dist
          force_orphan: true
